# Generated by Django 3.0.6 on 2020-12-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201212_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='confirm_password',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
