# Generated by Django 3.0.6 on 2020-12-29 09:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201229_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='SOME STRING'),
        ),
    ]
